version: "3.8"

services:

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_USERNAME: 'root'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'db'
    volumes:
      - db_data:/var/lib/db_data

  back:
    build: ../back-end
    depends_on: 
      - db
    environment:
      NODE_ENV: development
    restart: always
    ports:
      - 3000:3000

  front:
    build: ../front-end
    depends_on:
      - back
    ports:
      - 80:4200
    

volumes:
  db_data: {}